exception = [26,37,88]
for nombre in range(0,101):
    if nombre not in exception:
        print(nombre)